### PR TITLE
 fixed login, add ssh inside dockerfile

### PR DESCRIPTION
**Pull request by Davidepad**
### Description of the Change

Fixed a problem related to the login in the D-Streamon gui.
Added ssh into the containers to make Ansible work

### Alternate Designs

No other alternative, Ansible requires ssh to work

### Benefits

Now D-streamon master is able to configure the d-streamon slave. And everything works via GUI

### Possible Drawbacks

I have not found any negative effects

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Can you please add some details about the pull request by filling the template?

Please note that adding a running SSH daemon in a container is considered a bad practice. Why do you need such feature?

If you need to inspect a running container just open a new shell with `docker exec -it container_id /bin/bash`

**Comment by Davidepad** [comment]
@ferrarimarco I added ssh inside the containers not to inspect them (I know the exec command) but because D-Streamon master uses Ansible to configure the D-Streamon slave.

Ansible needs ssh to work.

The issues you sent me are related to the D-Streamon core (inside the streamon folder).

That is not code written by me, anyway I can take a look and try to remove the issues

**Comment by ferrarimarco** [comment]
Great, thanks

**Comment by Davidepad** [comment]
@ferrarimarco I took a look and there are issues that are part of the code not mine and some are inside libraries.

In addition, 16725 isssues are reported and I do not have the time to fix them all, they are really too many

**Pull request merged**
