### PR TITLE
updated d-streamon, updated libssl-dev, fixed d-streamon errors

### PR DESCRIPTION
**Pull request by Davidepad**

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Hi @Davidepad 

Can you please:
1. Squash these 4 commits in a single one
1. Write details about what you did in the commit message
1. Fix the errors in the build (see the Travis build output): some scripts are not passing the validation

Thanks!

**Comment by ferrarimarco** [comment]
@Davidepad one last request: can you please modify the commit message?

The first line (summary) should be no more than 72 chars. After that I'll wait for the build to finish and then I can merge. Also, it's not necessary to put an issue reference (like you did, issue #62) because there is no such issue :)

Thanks!

**Comment by Davidepad** [comment]
@ferrarimarco I modified the commit message, it should be better.

The build fails but it does not seem to be an error related to D-streamon.

**Comment by ferrarimarco** [comment]
@Davidepad I fixed the prelude-manager (and prewikka) builds. Can you please rebase this PR on development? So we can check we are at least able to build the D-Streamon images.

**Comment by Davidepad** [comment]
@ferrarimarco I saw the error logs, the changes in this branch repair that issue too.

I did the rebase.

**Comment by ferrarimarco** [comment]
@Davidepad see the error log, d-streamon-master is not building: https://travis-ci.org/scissor-project/open-scissor/builds/364495772

**Comment by Davidepad** [comment]
@ferrarimarco In my branch there are all the changes necessary to compile D-Streamon.

The last compilation of my branch compiles both the master and the slave:

https://travis-ci.org/scissor-project/open-scissor/builds/364243615

Accepting the PR for development and compiling D-Streamon should work.

**Comment by ferrarimarco** [comment]
I rebased the branch on the latest development. Waiting for the builds to complete...

**Pull request merged**
